name: cloud

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: "read"
  id-token: "write"

env:
  GAR_LOCATION: asia-east1
  PROJECT_ID: project-4b382091-2de2-4bd9-ad2
  REPOSITORY: shopee-dashboard
  IMAGE_NAME: app
  IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}
  GAR_BASE: asia-east1-docker.pkg.dev/project-4b382091-2de2-4bd9-ad2/shopee-dashboard/app

jobs:
  build-and-push:
    runs-on: ${{ github.ref_name == 'main' && 'ubuntu-latest' || 'self-hosted-dev' }}

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v3"
        with:
          workload_identity_provider: "projects/1586803717/locations/global/workloadIdentityPools/develop/providers/github-ci"
          service_account: "github@project-4b382091-2de2-4bd9-ad2.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"

      - name: "Docker Auth"
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      - name: "Build and Push Image"
        run: |
          TAG="${{ github.ref_name }}-${{ github.sha }}"
          FULL_PATH="${{ env.GAR_BASE }}"

          docker build -t "$FULL_PATH:$TAG" .
          docker push "$FULL_PATH:$TAG"

          docker tag "$FULL_PATH:$TAG" "$FULL_PATH:${{ github.ref_name }}"
          docker push "$FULL_PATH:${{ github.ref_name }}"

          echo "FINAL_IMAGE=$FULL_PATH:$TAG" >> $GITHUB_ENV

      - name: "Google Cloud Run Deploy"
        run: |
          gcloud run deploy shopee-dashboard \
            --image="${{ env.FINAL_IMAGE }}" \
            --region=${{ env.GAR_LOCATION }} \
            --platform=managed \
            --allow-unauthenticated \
            --quiet
